import { Amplify } from 'aws-amplify';
import config from '../amplify_outputs.json';

// Configure Amplify with backend resources
// This configuration is generated by: npx ampx sandbox
Amplify.configure(config);

export default Amplify;
